baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Cometadata development website'
theme = 'comet-theme'

# make better changes with our own styling in sass
# this get added to the end of the main style file
[params.custom_css]
name = "sass/_cometadata.scss"

[menu]
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "About"
    url        = "/about"
    weight     = 10
[[menu.main]]
    name       = "The Comet Model"
    url        = "/the-comet-model"
    weight     = 20
[[menu.main]]
    name       = "Projects"
    url        = "/projects"
    weight     = 30
[[menu.main]]
    name       = "Community"
    url        = "/community"
    weight     = 40
[[menu.main]]
    name       = "Blog"
    url        = "/blog"
    weight     = 50

