baseURL = 'https://example.org/'
# baseURL define in build command line for flexibility
locale = 'en-us'
title = 'COMET'
theme = 'comet-theme'

canonifyURLs = true

enableRobotsTXT = true

[permalinks]
  posts = "/blog/:slug/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  authors = 'authors'
  categories = 'categories'
  tags = 'tags'

[markup.goldmark.renderer]
    unsafe= true

# make better changes with our own styling in sass
# this get added to the end of the main style file
[params.custom_css]
name = "sass/_cometadata.scss"

[params]
  dateForm = "1/2/06"
  titleTagline = "COMET Richer Metadata. Together."
  description = "The COMET community is setting the standards for collaborative metadata enrichment practices and creating the shared infrastructure needed for trustworthy quality metadata to flow into the persistent identifier (PID) ecosystem we all rely on."
  defaultOgImage = "/images/og-default.jpg"

[menu]
[[menu.main]]
    name       = "COMET Model"
    url        = "/comet-model"
    weight     = 20
[[menu.main]]
    name       = "Projects"
    url        = "/projects"
    weight     = 30
[[menu.main]]
    name       = "Community"
    url        = "/community"
    weight     = 40
[[menu.main]]
    name       = "Blog"
    url        = "/posts"
    weight     = 50
[[menu.main]]
    name       = "About"
    url        = "/about"
    weight     = 60

